import { defineConfig } from 'oxlint';

export default defineConfig({
  '$schema': './node_modules/oxfmt/configuration_schema.json',
  categories: {
    correctness: 'warn'
  },
  env: {
    browser: true,
    node: true
  },
  globals: {
    defineProps: 'readonly',
    defineEmits: 'readonly',
    defineExpose: 'readonly',
    defineSlots: 'readonly',
    defineModel: 'readonly',
    withDefaults: 'readonly'
  },
  ignorePatterns: [
    '.next/**',
    '.vscode/**',
    'certificates/**',
    'dist/**',
    'docs/**',
    'node_modules/**',
    'public/**'
  ],
  plugins: [
    'import',
    'eslint',
    'jsdoc',
    'oxc',
    'unicorn',
    'vue'
  ],
  jsPlugins: [
    '@stylistic/eslint-plugin'
  ],
  rules: {
    '@stylistic/array-bracket-newline': [2, 'consistent'],
    '@stylistic/array-bracket-spacing': [2, 'never'],
    '@stylistic/arrow-parens': [2, 'always'],
    '@stylistic/arrow-spacing': [2],
    '@stylistic/block-spacing': [2],
    '@stylistic/brace-style': [2],
    '@stylistic/comma-dangle': [2, 'never'],
    '@stylistic/comma-spacing': [2],
    '@stylistic/comma-style': [2],
    '@stylistic/computed-property-spacing': [2],
    '@stylistic/dot-location': [2, 'property'],
    '@stylistic/eol-last': [2, 'always'],
    '@stylistic/function-call-spacing': [2, 'never'],
    '@stylistic/function-paren-newline': [2, 'consistent'],
    '@stylistic/generator-star-spacing': [2, { 'before': false, 'after': true }],
    '@stylistic/implicit-arrow-linebreak': [2, 'beside'],
    '@stylistic/indent': [2, 2],
    '@stylistic/key-spacing': [2, { 'beforeColon': false }],
    '@stylistic/keyword-spacing': [2, { 'before': true, 'after': true }],
    '@stylistic/new-parens': [2],
    '@stylistic/no-extra-semi': [2],
    '@stylistic/no-floating-decimal': [2],
    '@stylistic/no-mixed-operators': [2],
    '@stylistic/no-multi-spaces': [2],
    '@stylistic/no-multiple-empty-lines': [2, { max: 4 }],
    '@stylistic/no-trailing-spaces': [2],
    '@stylistic/no-whitespace-before-property': [2],
    '@stylistic/object-curly-newline': [2, { consistent: true }],
    '@stylistic/object-curly-spacing': [2, 'always'],
    '@stylistic/quotes': [2, 'single'],
    '@stylistic/rest-spread-spacing': [2, 'never'],
    '@stylistic/semi-spacing': [2, { 'before': false, 'after': true }],
    '@stylistic/semi-style': [2, 'last'],
    '@stylistic/semi': [2, 'always'],
    '@stylistic/space-before-blocks': [2],
    '@stylistic/space-before-function-paren': [2, 'always'],
    '@stylistic/space-infix-ops': [2],
    '@stylistic/template-curly-spacing': [2],
    '@stylistic/template-tag-spacing': [2, 'never'],
    'eslint/accessor-pairs': [2],
    'import/export': [2],
    'import/named': [2],
    'import/no-commonjs': [2],
    'import/no-duplicates': [2],
    'import/no-dynamic-require': [2],
    'import/no-empty-named-blocks': [2],
    'import/no-relative-parent-imports': [2],
    'import/no-self-import': [2],
    'import/unambiguous': [0],
    'jsdoc/check-property-names': [1],
    'jsdoc/empty-tags': [1],
    'jsdoc/implements-on-classes': [2],
    'jsdoc/no-blank-blocks': [2],
    'jsdoc/no-defaults': [2],
    'jsdoc/require-param-description': [0],
    'jsdoc/require-param-name': [1],
    'jsdoc/require-param-type': [1],
    'jsdoc/require-property-description': [0],
    'jsdoc/require-property-name': [1],
    'jsdoc/require-property-type': [1],
    'jsdoc/require-property': [1],
    'jsdoc/require-returns-description': [0],
    'jsdoc/require-returns-type': [1],
    'jsdoc/require-returns': [1],
    'jsdoc/require-yields-description': [0],
    'jsdoc/require-yields-type': [1],
    'jsdoc/require-yields': [1],
    'oxc/bad-bitwise-operator': [2],
    'oxc/branches-sharing-code': [1],
    'oxc/misrefactored-assign-op': [1],
    'oxc/no-accumulating-spread': [2],
    'oxc/no-async-await': [0],
    'unicorn/consistent-empty-array-spread': [2],
    'unicorn/consistent-existence-index-check': [2],
    'unicorn/consistent-function-scoping': [2],
    'unicorn/consistent-template-literal-escape': [2],
    'unicorn/empty-brace-spaces': [2],
    'unicorn/error-message': [2],
    'unicorn/escape-case': [2],
    'unicorn/explicit-length-check': [2],
    'unicorn/explicit-timer-delay': [2],
    'unicorn/filename-case': [2, { 'case': 'kebabCase' }],
    'unicorn/no-accessor-recursion': [2],
    'unicorn/no-array-callback-reference': [0],
    'unicorn/no-array-for-each': [0], // ENABLE THIS LATER
    'unicorn/no-array-method-this-argument': [2],
    'unicorn/no-array-reverse': [2],
    'unicorn/no-array-sort': [2],
    'unicorn/no-await-expression-member': [2],
    'unicorn/no-confusing-array-with': [2],
    'unicorn/no-document-cookie': [2],
    'unicorn/no-hex-escape': [2],
    'unicorn/no-immediate-mutation': [2],
    'unicorn/no-instanceof-array': [2],
    'unicorn/no-length-as-slice-end': [2],
    'unicorn/no-lonely-if': [2],
    'unicorn/no-magic-array-flat-depth': [2],
    'unicorn/no-nested-ternary': [2],
    'unicorn/no-new-buffer': [2],
    'unicorn/no-null': [0],
    'unicorn/no-object-as-default-parameter': [2],
    'unicorn/no-typeof-undefined': [2],
    'unicorn/no-unnecessary-array-flat-depth': [2],
    'unicorn/no-unnecessary-array-splice-count': [2],
    'unicorn/no-unnecessary-await': [2],
    'unicorn/no-unnecessary-slice-end': [2],
    'unicorn/no-unreadable-array-destructuring': [2],
    'unicorn/no-unreadable-iife': [2],
    'unicorn/no-useless-iterator-to-array': [2],
    'unicorn/no-useless-switch-case': [2],
    'unicorn/prefer-add-event-listener': [2],
    'unicorn/prefer-array-find': [2],
    'unicorn/prefer-array-flat-map': [2],
    'unicorn/prefer-array-flat': [2],
    'unicorn/prefer-array-index-of': [2],
    'unicorn/prefer-array-some': [2],
    'unicorn/prefer-at': [2],
    'unicorn/prefer-classlist-toggle': [2],
    'unicorn/prefer-date-now': [2],
    'unicorn/prefer-default-parameters': [2],
    'unicorn/prefer-includes': [2],
    'unicorn/prefer-logical-operator-over-ternary': [2],
    'unicorn/prefer-math-min-max': [2],
    'unicorn/prefer-modern-dom-apis': [2],
    'unicorn/prefer-modern-math-apis': [2],
    'unicorn/prefer-native-coercion-functions': [2],
    'unicorn/prefer-negative-index': [2],
    'unicorn/prefer-number-coercion': [2],
    'unicorn/prefer-number-properties': [2],
    'unicorn/prefer-object-from-entries': [2],
    'unicorn/prefer-query-selector': [2],
    'unicorn/prefer-regexp-test': [2],
    'unicorn/prefer-set-has': [2],
    'unicorn/prefer-single-call': [2],
    'unicorn/prefer-string-raw': [2],
    'unicorn/prefer-string-replace-all': [2],
    'unicorn/prefer-string-slice': [2],
    'unicorn/prefer-string-trim-start-end': [2],
    'unicorn/prefer-ternary': [2],
    'unicorn/switch-case-braces': [2, 'always'],
    'unicorn/switch-case-break-position': [2],
    'vue/define-props-destructuring': [2, { 'destructure': 'never' }],
    'vue/no-arrow-functions-in-watch': [2],
    'vue/no-async-in-computed-properties': [2],
    'vue/no-export-in-script-setup': [2],
    'vue/no-expose-after-await': [2],
    'vue/no-import-compiler-macros': [2],
    'vue/no-reserved-component-names': [2],
    'vue/no-reserved-keys': [2],
    'vue/no-reserved-props': [2],
    'vue/no-shared-component-data': [2],
    'vue/no-side-effects-in-computed-properties': [2],
    'vue/no-this-in-before-route-enter': [2],
    'vue/no-watch-after-await': [2],
    'vue/prefer-import-from-vue': [2],
    'vue/prop-name-casing': [2, 'camelCase'],
    'vue/require-default-export': [2],
    'vue/require-default-prop': [2],
    'vue/require-prop-type-constructor': [2],
    'vue/require-prop-types': [2],
    'vue/valid-define-emits': [2],
    'vue/valid-define-options': [2],
    'vue/valid-define-props': [2],
    'arrow-body-style': [0],
    'block-scoped-var': [2],
    'class-methods-use-this': [2],
    'complexity': [2],
    'consistent-return': [2],
    'constructor-super': [2],
    'curly': [2, 'all'],
    'default-case-last': [2],
    'default-case': [2],
    'default-param-last': [2],
    'eqeqeq': [2],
    'for-direction': [2],
    'getter-return': [2],
    'guard-for-in': [2],
    'new-cap': [2],
    'no-alert': [2],
    'no-array-constructor': [2],
    'no-async-promise-executor': [2],
    'no-await-in-loop': [2],
    'no-caller': [2],
    'no-case-declarations': [2],
    'no-class-assign': [2],
    'no-compare-neg-zero': [2],
    'no-cond-assign': [2],
    'no-console': [0, { 'allow': ['warn', 'error'] }],
    'no-const-assign': [2],
    'no-constant-binary-expression': [2],
    'no-constant-condition': [2],
    'no-constructor-return': [2],
    'no-delete-var': [2],
    'no-div-regex': [2],
    'no-dupe-class-members': [2],
    'no-dupe-else-if': [2],
    'no-dupe-keys': [2],
    'no-duplicate-case': [2],
    'no-duplicate-imports': [2],
    'no-else-return': [2],
    'no-empty-character-class': [2],
    'no-empty-function': [1],
    'no-empty-pattern': [2],
    'no-empty-static-block': [2],
    'no-empty': [2],
    'no-eq-null': [2],
    'no-eval': [2],
    'no-ex-assign': [2],
    'no-extend-native': [2],
    'no-extra-bind': [2],
    'no-extra-boolean-cast': [2],
    'no-extra-label': [2],
    'no-fallthrough': [2],
    'no-func-assign': [2],
    'no-global-assign': [2],
    'no-implicit-globals': [2],
    'no-implied-eval': [2],
    'no-import-assign': [2],
    'no-inline-comments': [0],
    'no-inner-declarations': [2],
    'no-invalid-regexp': [2],
    'no-irregular-whitespace': [2],
    'no-iterator': [2],
    'no-label-var': [2],
    'no-labels': [2],
    'no-lonely-if': [2],
    'no-loop-func': [2],
    'no-loss-of-precision': [2],
    'no-misleading-character-class': [2],
    'no-multi-assign': [2],
    'no-multi-str': [2],
    'no-nested-ternary': [2],
    'no-new-func': [2],
    'no-new-native-nonconstructor': [2],
    'no-new-wrappers': [2],
    'no-new': [2],
    'no-nonoctal-decimal-escape': [2],
    'no-obj-calls': [2],
    'no-object-constructor': [2],
    'no-param-reassign': [2],
    'no-plusplus': [2],
    'no-promise-executor-return': [2],
    'no-proto': [2],
    'no-prototype-builtins': [2],
    'no-redeclare': [2],
    'no-regex-spaces': [2],
    'no-restricted-properties': [2],
    'no-return-assign': [2],
    'no-script-url': [2],
    'no-self-assign': [2],
    'no-self-compare': [2],
    'no-setter-return': [2],
    'no-shadow-restricted-names': [2],
    'no-shadow': [2],
    'no-sparse-arrays': [2],
    'no-template-curly-in-string': [2],
    'no-this-before-super': [2],
    'no-throw-literal': [2],
    'no-undef': [2],
    'no-undefined': [0],
    'no-underscore-dangle': [2, { allow: ['_esi', 'containerElem_'] }],
    'no-unexpected-multiline': [2],
    'no-unmodified-loop-condition': [2],
    'no-unneeded-ternary': [2],
    'no-unreachable-loop': [2],
    'no-unreachable': [2],
    'no-unsafe-finally': [2],
    'no-unsafe-negation': [2],
    'no-unsafe-optional-chaining': [2],
    'no-unused-expressions': [2],
    'no-unused-labels': [2],
    'no-unused-private-class-members': [2],
    'no-unused-vars': [2, { args: 'none', ignoreRestSiblings: true, caughtErrors: 'none' }],
    'no-use-before-define': [2, { functions: false }],
    'no-useless-assignment': [2],
    'no-useless-backreference': [2],
    'no-useless-call': [2],
    'no-useless-catch': [2],
    'no-useless-computed-key': [2],
    'no-useless-concat': [2],
    'no-useless-constructor': [2],
    'no-useless-escape': [2],
    'no-useless-rename': [2],
    'no-var': [2],
    'no-void': [2],
    'no-with': [2],
    'object-shorthand': [2],
    'prefer-arrow-callback': [2],
    'prefer-const': [2],
    'prefer-destructuring': [2],
    'prefer-named-capture-group': [0],
    'prefer-object-has-own': [2],
    'prefer-object-spread': [2],
    'prefer-rest-params': [2],
    'prefer-spread': [2],
    'prefer-template': [2],
    'radix': [2],
    'require-await': [1],
    'require-yield': [2]
  },
  overrides: [
    {
      'files': ['*.test.js', '*.spec.ts'],
      rules: {
        'no-loss-of-precision': 'off',
        'no-undefined': 'off',
        'require-await': 'off'
      }
    },
    {
      'files': ['./scripts/*.js'],
      rules: {
        'no-console': 'off'
      }
    }
  ]
});
